### ISSUE TITLE
Playback failure popup

### ISSUE THREAD

**Issue by faisonusa** [mrgsi/tmdbh.players#4]
After importing the list of players. I am getting a random playback failure. I have to cancel the popup before accessing what I am looking to play. If I select something to play before the playback failure then It will stop the play and I have to start over. Just annoying.

**Comment by mrgsi** [comment]
Been there, done that. Players either work, or don't work so if it's random it sounds like the add-on can't find a source for whatever you are trying to play. If it happens all the time, then let me know which player so I can test it on my end. That delayed pop-up can be a pain, but that's something for Themoviedb-Helper dev to look at, the players don't control that message.

**Comment by faisonusa** [comment]
Hello,  It happens when using The Crew addon and the Thepromise addonSent from my iPhoneOn Jul 20, 2023, at 3:22 PM, G-Man ***@***.***> wrote:﻿
Been there, done that. Players either work, or don't work so if it's random it sounds like the add-on can't find a source for whatever you are trying to play. If it happens all the time, then let me know which player so I can test it on my end. That delayed pop-up can be a pain, but that's something for Themoviedb-Helper dev to look at, the players don't control that message.

**Comment by mrgsi** [comment]
I tested both those players this morning and was able to play both movies and tv shows on Kodi 20.2, so the players work. If the same video plays in the add-on but not with the player, try updating the players. Keep in mind, if you did any changes to a player with the Helper setting, you will need to go back into settings and reset each player back to default. Otherwise the Helper will continue to use the modified old version instead of the updated new version. After it's reset you can go back in and re-edit if you want.

**Comment by faisonusa** [comment]
Thanks
